version: '3.7'
services:
  musicplayer-client:
    image: music-image
    ports:
      - "81:81"
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - muisc_files_volume:/musicplayer/files

    command: ["nginx", "-g", "daemon off;"]
    networks:
      - music_network
    
networks:
  music_network:
    external: true
volumes:
  muisc_files_volume:
    external: true